version: '3'
services:
  paper:
    container_name: paper
    build: .
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${ROOT}:/paper
    ports:
      - 25565:25565
    stdin_open: true
    tty: true
