version: '3'
services:
  paper:
    container_name: paper
    image: rneacsu/paper
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - JAVA_OPTS=${JAVA_OPTS}
      - PAPER_OPTS=${PAPER_OPTS}
    volumes:
      - ${ROOT}:/paper
    ports:
      - 25565:25565
    stdin_open: true
    tty: true
